### ISSUE TITLE
change "developers" to industry pros

### ISSUE THREAD

**Issue by nohorse** [MVPStudio/mvp-studio-web-cms#27]
![image](https://user-images.githubusercontent.com/311063/53590982-d3953a80-3b47-11e9-816b-b89b0ff8826a.png)

because we want designers, product orners, PMs etc too

![image](https://user-images.githubusercontent.com/311063/53591012-ed368200-3b47-11e9-9982-a0b44d3886fd.png)

**Comment by mckelveygreg** [comment]
changed in this week's branch
